CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    lastModifiedAt TIMESTAMP NOT NULL,
    version INTEGER NOT NULL,
    userName VARCHAR(20) NOT NULL,
    hash VARCHAR(200) NOT NULL,
    token VARCHAR(200)
)