CREATE TABLE IF NOT EXISTS stacks (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    lastModifiedAt TIMESTAMP NOT NULL,
    version INTEGER NOT NULL,
    clientId VARCHAR (8) NOT NULL REFERENCES clients(id),
    name VARCHAR (30) NOT NULL
)